### ISSUE TITLE
mapa mental

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/mapa-mental-web-3-bg55-a#1]
[Mapa mental la web 3.0.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-bg55-a/files/8375016/Mapa.mental.la.web.3.0.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by josealfredo79** [comment]
Falta la calificacion...

**Comment by josealfredo79** [comment]
Calificacion: 19  Bien hecho y revisado.
